In [1]:
import os
import numpy as np
import pandas as pd

In [3]:
PREF = 'f103'

KEY = 'card_id'

stats = ['min', 'max', 'mean', 'median', 'std', 'var', 'skew', 'count']

In [4]:
PATH = os.path.join('..', 'data')

historical_transactions = pd.read_csv(os.path.join(PATH, 'historical_transactions.csv'))
historical_transactions['installments'] = historical_transactions['installments'].astype(int)

In [7]:
num_aggregations = {
    'purchase_amount': stats,
    'installments': stats
}

In [8]:
grouped = historical_transactions.groupby(['card_id', 'authorized_flag'])
agg = grouped.agg(num_aggregations)
agg.columns = ['_'.join(col).strip() for col in agg.columns.values]
agg.reset_index(inplace=True)

In [9]:
agg.head()

,card_id,authorized_flag,purchase_amount_min,purchase_amount_max,purchase_amount_mean,purchase_amount_median,purchase_amount_std,purchase_amount_var,purchase_amount_skew,purchase_amount_count,installments_min,installments_max,installments_mean,installments_median,installments_std,installments_var,installments_skew,installments_count
0,C_ID_00007093c1,0,-0.728876,1.507069,-0.411485,-0.569219,0.430059,0.184951,3.035875,35,1,3,1.285714,1.0,0.667367,0.445378,2.120415,35
1,C_ID_00007093c1,1,-0.728876,1.206539,-0.547746,-0.596643,0.237426,0.056371,4.183977,114,1,6,1.289474,1.0,0.795159,0.632278,3.514956,114
2,C_ID_0001238066,0,-0.596643,-0.596643,-0.596643,-0.596643,0.000000,0.000000,0.000000,3,1,1,1.000000,1.0,0.000000,0.000000,0.000000,3
3,C_ID_0001238066,1,-0.734887,0.768095,-0.588811,-0.650122,0.192614,0.037100,4.006112,120,-1,10,1.625000,1.0,1.501050,2.253151,2.893080,120
4,C_ID_0001506ef0,0,-0.740491,-0.708590,-0.726445,-0.728350,0.016203,0.000263,0.218985,4,0,1,0.250000,0.0,0.500000,0.250000,2.000000,4

In [10]:
agg_Y = agg[agg.authorized_flag == 1].add_prefix('Y_')
agg_Y = agg_Y.rename(columns={'Y_card_id': 'card_id'})
agg_N = agg[agg.authorized_flag == 0].add_prefix('N_')
agg_N = agg_N.rename(columns={'N_card_id': 'card_id'})

In [16]:
agg_Y.head()

,card_id,Y_purchase_amount_min,Y_purchase_amount_max,Y_purchase_amount_mean,Y_purchase_amount_median,Y_purchase_amount_std,Y_purchase_amount_var,Y_purchase_amount_skew,Y_purchase_amount_count,Y_installments_min,Y_installments_max,Y_installments_mean,Y_installments_median,Y_installments_std,Y_installments_var,Y_installments_skew,Y_installments_count
1,C_ID_00007093c1,-0.728876,1.206539,-0.547746,-0.596643,0.237426,0.056371,4.183977,114,1,6,1.289474,1.0,0.795159,0.632278,3.514956,114
3,C_ID_0001238066,-0.734887,0.768095,-0.588811,-0.650122,0.192614,0.037100,4.006112,120,-1,10,1.625000,1.0,1.501050,2.253151,2.893080,120
5,C_ID_0001506ef0,-0.740491,1.493545,-0.511227,-0.700220,0.484575,0.234813,2.583079,62,0,0,0.000000,0.0,0.000000,0.000000,0.000000,62
7,C_ID_0001793786,-0.737892,4.554145,-0.132067,-0.447880,0.867916,0.753279,2.909714,189,0,0,0.000000,0.0,0.000000,0.000000,0.000000,189
9,C_ID_000183fdda,-0.737892,2.764788,-0.495595,-0.670693,0.523760,0.274325,4.088246,137,-1,10,1.788321,1.0,2.108912,4.447510,2.799102,137

In [15]:
del agg_Y['Y_authorized_flag']

In [13]:
agg_Y = agg_Y.groupby('card_id').agg(['mean', 'std', 'var', 'skew'])
agg_Y.columns = ['hist_'+'_'.join(col).strip() for col in agg_Y.columns.values]
agg_Y = agg_Y.reset_index()
agg_Y = agg_Y.rename(columns={'hist_card_id': 'card_id'})

KeyboardInterrupt:

In [ ]:
agg_N = agg_N.groupby('card_id').agg(['mean', 'std', 'var', 'skew'])
agg_N.columns = ['hist_'+'_'.join(col).strip() for col in agg_N.columns.values]
agg_N = agg_N.reset_index()
agg_N = agg_N.rename(columns={'hist_card_id': 'card_id'})